export const COPY = {
  eyebrow: 'Từ thời đồ đá đến nay',
  title: 'VIỆT NAM',
  subtitle: 'Mở mang bờ cõi',
  loading: 'Đang dựng non sông…',
  loadError: 'Không tải được dữ liệu bản đồ.',
  retry: 'Thử lại',
  noWebGL:
    'Trình duyệt của bạn không hỗ trợ WebGL nên không hiển thị được bản đồ 3D. Dưới đây là các mốc lịch sử dạng văn bản.',
  hint: 'Kéo để xoay · lăn để thu phóng · rê vào lãnh thổ để xem chính thể',
  flagKind: {
    national: 'Quốc kỳ',
    banner: 'Cờ hiệu',
    reconstructed: 'Cờ phục dựng',
    symbol: 'Biểu tượng'
  },
  lowConfidence: 'Một phần ranh giới ở mốc này là ước đoán',
  sources: 'Nguồn',
  polities: 'Các chính thể',
  capital: 'Kinh đô',
  period: 'Thời gian tồn tại',
  flagNote: 'Về lá cờ',
  flagSourceFallback: 'Wikimedia Commons',
  play: 'Tự chạy',
  pause: 'Tạm dừng',
  prev: 'Mốc trước',
  next: 'Mốc sau',
  timelineLabel: 'Dòng thời gian',
  eraBandLabel: 'Các thời kỳ',
  jumpToEra: 'Tới thời kỳ',
  eraCardAnnouncementPrefix: 'Thời kỳ',
  eraRangeOngoing: 'nay',
  credits: 'Nguồn & ghi công',
  close: 'Đóng',
  back: 'Quay lại toàn cảnh',
  sidePanelToggle: 'Thông tin',
  creditsBoundariesLabel: 'Ranh giới hành chính:',
  creditsBoundariesSourceName: 'geoBoundaries',
  creditsBoundariesSourceUrl: 'https://www.geoboundaries.org',
  creditsBoundariesNote:
    '(CC BY 3.0 IGO / CC BY 4.0 / PDDL). Lãnh thổ lịch sử được ghép từ ranh giới cấp huyện hiện đại nên chỉ là xấp xỉ.',
  creditsMapTechnique: 'Kỹ thuật dựng bản đồ tham khảo từ dự án vietnam-3d-map (holetex.com).',
  creditsFlagsHeading: 'Cờ và biểu tượng',
  creditsFlagsOnLandNote:
    'Cờ vẽ trên lãnh thổ là quốc kỳ hoặc cờ hiệu gốc của mỗi chính thể; cờ riêng theo từng triều đại hoặc quốc hiệu chỉ hiện trong thẻ chi tiết chính thể.',
  creditsNoCredit: 'Biểu tượng tự vẽ cho dự án.',
  creditsMusicHeading: 'Nhạc nền',
  musicOn: 'Bật nhạc nền',
  musicOff: 'Tắt nhạc nền'
} as const;
